flashing/index: Power off Jetson DUT on container flash failure
This should allow the DUT to cool off while not in use, because in rcm-boot mode the fan is not spinning.

Also, with this commit we check if the following sporadic error observed on J3010 disappears:

  ECID is
  Board ID() version() sku() revision()
  Chip SKU(00:00:00:D3) ramcode() fuselevel(fuselevel_production)   board_FAB()
  emc_opt_disable_fuse:(0)
  Error: Unrecognized module SKU

Change-type: patch
Signed-off-by: Alexandru Costache <alexandru@balena.io